## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

name: Apache Jena CI
# Manual
on: workflow_dispatch

#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Build with Maven
      run: mvn -DskipTest clean install -Pdev --file pom.xml

  publish:
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: 
      - build
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Publish package
        run: mvn clean deploy -Dmaven.test.skip=true -Drevision=${{github.ref_name}} -DrepositoryId=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

