# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

# Manual
on: workflow_dispatch

#on:
# release:
#  types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Configure Maven
      run: mvn clean deploy -DskipTests

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secretes.GITHUB_TOKEN }}
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
